# Generated by Django 4.0.1 on 2022-01-25 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_alter_news_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='numbers_of_views',
            field=models.IntegerField(default=0),
        ),
    ]
